name: wallet
description: "Wallet is a Flutter project designed to store card information
  locally on the device, ensuring that the data is secure and cannot be stolen,
  as the application does not have internet access. The app is optimized for
  efficiency, allowing users to quickly copy card details for transactions."
publish_to: "none"
version: 1.0.20+23

environment:
  sdk: ^3.10.4
  flutter: ^3.38.5

dependencies:
  barcode_scan2: ^4.4.0
  barcode_widget: ^2.0.4
  crypto: ^3.0.5
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.0
  flutter_staggered_animations: ^1.1.1
  image_picker: ^1.2.0
  local_auth: ^2.3.0
  lottie: ^3.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  provider: ^6.1.2
  # screen_brightness: ^2.1.7
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/network/

  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: ZenDots
      fonts:
        - asset: assets/fonts/ZenDots-Regular.ttf
    - family: ZSpace
      fonts:
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
